spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 740746317889-kbbpujq593sgheof2fdsiugg5b09goii.apps.googleusercontent.com
            client-secret: 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

